# Generated by Django 6.1.1 on 2026-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='non_vegeterian',
            field=models.BooleanField(default=False),
        ),
    ]
