# Generated by Django 6.1.1 on 2026-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_item_non_vegeterian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='non_vegeterian',
            field=models.BooleanField(default=True),
        ),
    ]
