# Generated by Django 6.1.1 on 2026-09-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_item_non_vegeterian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='non_vegeterian',
        ),
    ]
