# Generated by Django 6.1.1 on 2026-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_item_non_vegeterian'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
