# Generated by Django 6.1.1 on 2026-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
