# Generated by Django 6.1.1 on 2026-09-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_restaurant_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location_url',
        ),
    ]
